name: Golang CI

env:
  GO_VERSION: '1.24.0'

on:
  push:
    branches:
      - main
    paths:
      - 'api/**.go'
      - 'api/go.mod'
      - 'api/go.sum'
  pull_request:
    branches:
      - feature/*
      - ci/*
    paths:
      - 'api/**.go'
      - 'api/go.mod'
      - 'api/go.sum'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: api/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=5m
          only-new-issues: true
          working-directory: api
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: api/go.sum

      - name: Test
        run: go test -v ./...
        working-directory: api
